### PR TITLE
Added edit functionality to the Create component

### PR DESCRIPTION
**Pull request by joseweig**
Changes:
- Added edit functionality to the Create component
- Added Edit button to Tasks table
- Changed comment field input to InputTextArea
- Renamed CreateTask to HandleValidSubmit
- Renamed Create button to Save

Note:
Might be a good idea to create a TaskService class to move responsibility away from components

### CODE REVIEW

**Comment by joseweig** [comment]
Shall we add an option to delete individual tasks?

**Comment by mystyq** [comment]
I think adding soft-delete functionality might be useful.  Right now the "clear all tasks" is strictly for demo/testing purposes, though archiving each individual record would be more realistic

**Comment by mystyq** [comment]
Also, another idea was to have the task not being able to be brought upstream.  If the task were to change from `Staged` -> `In Progress` for example, we would lock down the ability to move back into a `Staged` state.  I suppose the goal would be to incentivize better usage of tasks over time.  Some people like to multi-task, though, so they might move multiple tasks into an `In Progress` state and leave it there, skewing the aspect of productivity

If we make it so tasks can't come back upstream, it might encourage users to create more functional tasks

If we leave the system flexible, with soft-delete functionality, there could be room for error which is another good measure

**Comment by mystyq** [comment]
In any case, it would be good to add change tracking to a task.  Any state changes/editing of tasks - should have a snapshot of the change

**Comment by mystyq** [comment]
@joseweig What do you mean about the TaskService class?  Like to inject its behavior into the component?

**Comment by joseweig** [comment]
> @joseweig What do you mean about the TaskService class? Like to inject its behavior into the component?

Yes. Move the dbContext and business logic pertaining to the Task model to its own service class (TaskService) in order to separate the data access layer from the UI. Keeps the UI or API layer clean from direct data access code, leading to a more modular application.

I can work on it and submit a pull request so you can review it.

I can also work on the logic for not being able to bring a task upstream if you like.

**Comment by mystyq** [comment]
Sure, sounds good.

**Pull request merged**
